### ISSUE TITLE
stream.pause()?

### ISSUE THREAD

**Issue by jwalton** [stream-utils/pause#11]
I feel like I'm missing something.  Instead of buffering (potentially large amounts of) data in memory, why would you not simply call `stream.pause()`?  `stream.pause()` should exert back-pressure on the sender and stop them from sending more data until we're ready to accept it.

**Comment by jwalton** [comment]
I thought as much; ran into a reference to `pause` when I was reading the source to passport.  Just wanted to make sure I wasn't crazy.  :)

**Comment by jwalton** [comment]
Yeah, it's old code, and thankfully hidden behind an undocumented switch.

I've been writing in node since the 0.6 days.  It still feels weird that Node 4 is end-of-life, and I can remove it from my travis.yml files, to be honest.  :P

**Comment by dougwilson** [comment]
Oh, haha. I took a look at the original PR that added it and it was around when 0.10 and streams2 came out. Looks like they rather have people use node 0.10+ than the switch anyway, which is probably why it's undocumented.

It's funny the only reason I took over this module was to make a release because of that npm change where it would warn on installing any package that didn't have a license defined in package.json haha.
